routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Mail\ApprovalRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;

Auth::routes();

//Route::get('/',function(){
//
//    Mail::to(['email'=>'marvincollins14@gmail.com'])
//        ->cc(\Esl\helpers\Constants::EMAILS_CC)
//        ->send(new \App\Mail\ProjectInvoice(['message'=>'System Under Maintenance',
//            'body'=>'System is Down for Maintenance'],'System Under maintenance'));
//    return view('404');
//
//
////    echo "check your mailtrap";
//
//});

Route::get('/testmail',function(){
    Mail::to(['email'=>'marvincollins14@gmail.com'])
        ->cc(['evans.ngala@esl-eastafrica.com'])
        ->send(new ApprovalRequest([
            'user' => 'Demo Demo',
            'url'=>'/quotation/view/1'],'Approval Request'));

    echo "check your mailtrap";

});
Route::get('/quotation/preview/{id}', 'QuotationController@previewQuotation');
Route::get('/quotation/download/{id}', 'QuotationController@downloadQuotation');
Route::get('/proforma/download/{id}', 'ProformaController@downloadProforma');
Route::get('/quotation/customer/accepted/{id}', 'QuotationController@customerAccept');
Route::get('/quotation/customer/declined/{id}', 'QuotationController@customerDecline');
Route::get('/view-po/{purchase_order_id}', 'PurchaseOrderController@showPurchaseOrder');


Route::group(['middleware' => ['auth']], function (){
    //    po
    Route::get('/generate-po/{quotation_id}', 'PurchaseOrderController@generatePo');
    Route::get('/approve-po/{purchase_order_id}', 'PurchaseOrderController@approvePurchaseOrder');
    Route::get('/disapprove-po/{purchase_order_id}', 'PurchaseOrderController@disapprovePurchaseOrder');

    Route::get('/', 'HomeController@dashboard');
    Route::resource('/customers', 'CustomerController');
    Route::resource('/manage-users', 'ManageController');
    Route::get('/create-role', 'ManageController@createRole');
    Route::delete('delete-role/{id}', 'ManageController@deleteRole');
    Route::get('/roles', 'ManageController@roleIndex');
    Route::post('/store-role', 'ManageController@storeRole');
    Route::get('/customer-request/{customer_id}/{customer_type}', 'CustomerRequestController@customerRequest');
    Route::resource('/good-types', 'GoodTypeController');
    Route::resource('/container-types', 'ContainerTypeController');
    Route::resource('/leads', 'LeadController');
    Route::resource('/tariffs', 'TariffController');
    Route::resource('/departments', 'DepartmentController');
    Route::post('/search-lead', 'LeadController@searchLeads');
    Route::post('/error', 'DepartmentController@error');
    Route::post('/search-dms', 'DmsController@searchDms');
    Route::post('/update-berth', 'DmsController@updateBerth');
    Route::post('/search-customer', 'CustomerController@ajaxSearch');
    Route::get('/get-customer/{dclink}', 'CustomerController@getCustomer');
    Route::get('/get-vendor/{id}', 'PurchaseOrderController@getVendor');
    Route::post('/search-vendor', 'PurchaseOrderController@searchSupplier');
    Route::post('/add-purchase-order', 'PurchaseOrderController@addPurchaseOrder');
    Route::post('/update-vessel-details', 'CustomerController@updateVessel');
    Route::post('/vessel-details', 'CustomerController@vesselDetails');
    Route::post('/others-vessel-details', 'CustomerController@oVesselDetails');
    Route::post('/voyage-details', 'CustomerController@voyageDetails');
    Route::post('/consignee-details', 'CustomerController@consigneeDetails');
    Route::post('/cargo-details', 'CustomerController@cargoDetails');
    Route::post('/update-cargo-details', 'CustomerController@updateCargoDetails');
    Route::post('/delete-cargo', 'CustomerController@deleteCargo');
    Route::post('/quotation-service', 'QuotationServiceController@addQuotationService');
    Route::post('/quotation-service-delete', 'QuotationServiceController@deleteQuotationService');
    Route::get('/quotation/{id}', 'QuotationController@showQuotation');
    Route::get('/proforma/{id}', 'ProformaController@showQuotation');
    Route::get('/my-pdas', 'QuotationController@myPdas');
    Route::get('/all-pdas', 'QuotationController@allPdas');
    Route::get('/pdas/{status}', 'QuotationController@pdaStatus');
    Route::get('/quotation/view/{id}', 'QuotationController@viewQuotation');
    Route::post('/client/quotation/send/', 'QuotationController@sendToCustomer');
    Route::get('/all-notifications', 'NotificationController@index');
    Route::get('/agency', 'AgencyController@index');
    Route::post('/agency/approve', 'AgencyApprovalController@approve');
    Route::post('/agency/remark', 'AgencyApprovalController@addRemark');
    Route::post('/agency/disapprove', 'AgencyApprovalController@revision');
    Route::post('/agency/checked', 'AgencyApprovalController@checked');
    Route::get('/notifications/{id}', 'NotificationController@show');
    Route::get('/quotation/request/{id}', 'QuotationController@requestQuotation');
//Route::get('/quotation/{id}/pdf', 'QuotationController@pdfQuotation');
    Route::post('/update-service', 'QuotationServiceController@updateService');
    Route::post('/notifying', 'NotifyingPartyController@notifying');

//next stage
    Route::get('/quotation/convert/{id}', 'QuotationController@convertCustomer');
    Route::get('/bill-of-lading/{id}', 'BillOfLandingController@edit');
    Route::get('/test/', 'BillOfLandingController@test');
//dms
    Route::get('/dms', 'DmsController@index');
    Route::get('/dms/edit/{id}', 'DmsController@edit');
    Route::get('/dms/complete/{id}', 'DmsController@complete');
    Route::get('/generate/laytime/{id}', 'DmsController@generateLayTime');
    Route::get('/generate/sof/{id}', 'DmsController@generateSof');
    Route::post('/dms/store/', 'DmsController@store');
    Route::post('/dms/add/sof', 'DmsController@addSof');
    Route::get('/dms/delete/sof/{id}', 'DmsController@deleteSof');
    Route::post('/update-dms/', 'DmsController@updateDms');
    Route::post('/vessel/doc/upload/', 'VesselDocsController@upload');
    Route::post('/add-remittance', 'QuotationController@addRemittance');
    Route::post('/reduce-remittance', 'QuotationController@reduceRemittance');
    Route::post('/consignee/do', 'GenerateDocument@doDoc');
    Route::post('/consignee/edo', 'GenerateDocument@edoDoc');
    Route::post('/generate-documents/cfs-ro', 'GenerateDocument@cfsDoc');
    Route::post('/generate-documents/manifest-in', 'GenerateDocument@inmanifestDoc');
//stage
    Route::resource('/stages', 'StageController');
    Route::resource('/other-services-type', 'ExtraServiceTypeController');
    Route::resource('/other-services', 'ExtraServiceController');
    Route::resource('/stage-components', 'StageComponentController');
//generate docs
    Route::get('/generate-documents/{type}/{id}', 'GenerateDocument@generateDocument');
    Route::resource('/project-cost', 'PettyCashController');
    Route::get('/approve-project-cost-request/{petty_cash_id}', 'PettyCashController@approve');
    Route::post('/service-cost', 'QuotationController@serviceCost');
});

app/Stage.php
<?php

namespace App;

use Esl\Repository\ESLModel;
use Illuminate\Database\Eloquent\Model;

class Stage extends ESLModel
{

    protected $fillable = ['name','service','description'];

    public function sComments()
    {
        return $this->hasMany(StageComment::class, 'stage_id', 'id');
    }

    public function components()
    {
        return $this->hasMany(StageComponent::class, 'stage_id', 'id');
    }
}

app/Http/Controllers/StageController.php
<?php

namespace App\Http\Controllers;

use App\Stage;
use Illuminate\Http\Request;

class StageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('stage.index')
            ->withStages(Stage::simplePaginate(25));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('stage.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Stage::create($request->all());

        return redirect('/stages');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Stage  $stage
     * @return \Illuminate\Http\Response
     */
    public function show(Stage $stage)
    {
        return view('stage.show')
            ->withStage($stage)
            ->withComponents($stage->components);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Stage  $stage
     * @return \Illuminate\Http\Response
     */
    public function edit(Stage $stage)
    {
        return view('stage.edit')
            ->withStage($stage);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Stage  $stage
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Stage $stage)
    {
        $stage->update($request->all());
        return redirect('/stages');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Stage  $stage
     * @return \Illuminate\Http\Response
     */
    public function destroy(Stage $stage)
    {
        $stage->delete();
        return redirect('/stages');
    }
}

resources/views/stage/create.blade.php
@extends('layouts.main')
@section('content')
    <div class="row page-titles m-b-0">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Dashboard</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </div>
        <div>
            <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add Stage</h4>
                        <form class="form-material m-t-40" action="{{ route('stages.store') }}" method="post">
                            {{ csrf_field() }}
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        <input type="text" required id="name" name="name" class="form-control" placeholder="Name">
                                    </div>
                                    <div class="form-group"><label for="service">Category</label>
                                        <select name="service" id="service" class="form-control select2">
                                            <option value="">Select</option>
                                            <option value="0">General</option>
                                            @foreach(\App\ExtraServiceType::all() as $value)
                                                <option value="{{$value->id}}">{{$value->name}}</option>
                                                @endforeach
                                        </select></div>
                                </div>

                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="description">Description</label>
                                            <input type="text" required id="description" name="description" class="form-control" placeholder="Description">
                                        </div>
                                        <div class="form-group">
                                            <br>
                                            <input class="btn pull-right btn-primary" type="submit" value="Save">
                                        </div>
                                    </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/stage/edit.blade.php
@extends('layouts.main')
@section('content')
    <div class="row page-titles m-b-0">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Dashboard</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </div>
        <div>
            <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Edit Stage</h4>
                        <form class="form-material m-t-40" action="{{ route('stages.update', $stage->id) }}" method="post">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        <input type="text" required id="name" value="{{ $stage->name }}" name="name" class="form-control" placeholder="Name">
                                    </div>
                                    <div class="form-group"><label for="service">Category</label>
                                        <select name="service" id="service" class="form-control select2">
                                            <option value="">Select</option>
                                            <option value="0">General</option>
                                            @foreach(\App\ExtraServiceType::all() as $value)
                                                <option value="{{$value->id}}">{{$value->name}}</option>
                                            @endforeach
                                        </select></div>
                                </div>

                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <input type="text" required id="description" value="{{ $stage->description }}" name="description" class="form-control" placeholder="Description">
                                    </div>
                                    <div class="form-group">
                                        <br>
                                        <input class="btn btn-block btn-primary" type="submit" value="Save">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/stage/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="row page-titles m-b-0">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Dashboard</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </div>
        <div>
            <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Stages <a href="{{ route('stages.create') }}" class="btn btn-primary pull-right">Add Stages</a></h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Type</th>
                                    <th>Description</th>
                                    <th>Created</th>
                                    <th class="text-right">Action</th>
                                </tr>
                                </thead>
                                <tbody id="customers">
                                @foreach($stages as $stage)
                                    <tr>
                                        <td>{{ ucwords($stage->name) }}</td>
                                        <td>{{ ucfirst($stage->service ==0 ? 'General' : \App\ExtraServiceType::findOrFail($stage->service)->name) }}</td>
                                        <td>{{ ucfirst($stage->description) }}</td>
                                        <td>{{ \Carbon\Carbon::parse($stage->created_at)->format('d-M-y') }}</td>
                                        <td class="text-right">
                                            <form action="{{ route('stages.destroy', $stage->id) }}" method="post">
                                                <a href=" {{ route('stages.edit', $stage->id) }}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
                                                <a href=" {{ route('stages.show', $stage->id) }}" class="btn btn-sm btn-primary"><i class="fa fa-eye"></i></a>
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                @can('can-delete')
                                                    <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
@endcan
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="footable pagination">
                                {{ $stages->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/stage/show.blade.php
@extends('layouts.main')
@section('content')
    <div class="row page-titles m-b-0">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Dashboard</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </div>
        <div>
            <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">{{ ucwords($stage->name)}} CheckList
                            <button class="btn btn-primary pull-right" data-toggle="modal" data-target=".bs-example-modal-lg"><i class="fa fa-plus"></i></button>
                        </h4>
                    </div>
                    <div class="card-body">
                        <table class="table table-boarded">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Type</th>
                                <th>Required</th>
                                <th>components</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody id="components">
                            @foreach($components as $item)
                                <tr>
                                    <td>{{ ucwords($item->name) }}</td>
                                    <td>{{ ucfirst($item->description) }}</td>
                                    <td>{{ $item->type }}</td>
                                    <td>{{ $item->required == true ? 'Yes' : 'No' }}</td>
                                    <td>{{ ($item->components != null ? implode(",",json_decode($item->components)) : $item->components ) }}</td>
                                    <td>
                                        <form action="{{ route('stage-components.destroy', $item->id) }}" method="post">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            @can('can-delete')
                                                <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
@endcan
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade bs-example-modal-lg" id="modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myLargeModalLabel">Add CheckList</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    <div class="col-12">
                                <form id="checklist" action="{{ route('stage-components.store') }}" onsubmit="event.preventDefault(); addChecklist(this, '{{ route('stage-components.store') }}')" method="post">
                                    {{ csrf_field() }}
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <input type="hidden" value="{{ $stage->id }}" name="stage_id" id="stage_id">
                                            <div class="form-group">
                                                <label for="name">Name</label>
                                                <input type="text"  required id="name" name="name" class="form-control" placeholder="Name">
                                            </div>
                                            <div class="form-group">
                                                <label for="type">Type</label>
                                                <select name="type" id="type" class="form-control">
                                                    <option value="file">File</option>
                                                    <option value="text">Text</option>
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label for="required">Required</label>
                                                <select name="required" id="required" class="form-control">
                                                    <option value="true">Yes</option>
                                                    <option value="false">No</option>
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label for="description">Description</label>
                                                <input type="text"  required id="description" name="description" class="form-control" placeholder="Description">
                                            </div>
                                            <div class="form-group">
                                                <label for="components">Sub Check List</label>
                                                <textarea name="components" id="components" cols="30" rows="10"
                                                          class="form-control"></textarea>
                                            </div>
                                            <div class="form-group">
                                                <input class="btn btn-block btn-primary" type="submit" value="Save">
                                            </div>

                                        </div>
                                    </div>
                                </form>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger waves-effect text-left" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

@endsection
@section('scripts')
    <script>
        function addChecklist(form, formUrl){

            var formId = form.id;
            var vessel = $('#'+formId);

            var data = vessel.serializeArray().reduce(function(obj, item) {
                obj[item.name] = item.value;
                return obj;
            }, {});

            axios.post(formUrl, data)
                .then(function (response) {
                    var details = response.data.success;

                    $('#components').append(details);
                    $('#modal').modal('hide');

                })
                .catch(function (response) {
                    console.log(response.data);
                });

        }
    </script>
@endsection