routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Mail\ApprovalRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;

Auth::routes();

//Route::get('/',function(){
//
//    Mail::to(['email'=>'marvincollins14@gmail.com'])
//        ->cc(\Esl\helpers\Constants::EMAILS_CC)
//        ->send(new \App\Mail\ProjectInvoice(['message'=>'System Under Maintenance',
//            'body'=>'System is Down for Maintenance'],'System Under maintenance'));
//    return view('404');
//
//
////    echo "check your mailtrap";
//
//});

Route::get('/testmail',function(){
    Mail::to(['email'=>'marvincollins14@gmail.com'])
        ->cc(['evans.ngala@esl-eastafrica.com'])
        ->send(new ApprovalRequest([
            'user' => 'Demo Demo',
            'url'=>'/quotation/view/1'],'Approval Request'));

    echo "check your mailtrap";

});
Route::get('/quotation/preview/{id}', 'QuotationController@previewQuotation');
Route::get('/quotation/download/{id}', 'QuotationController@downloadQuotation');
Route::get('/proforma/download/{id}', 'ProformaController@downloadProforma');
Route::get('/quotation/customer/accepted/{id}', 'QuotationController@customerAccept');
Route::get('/quotation/customer/declined/{id}', 'QuotationController@customerDecline');
Route::get('/view-po/{purchase_order_id}', 'PurchaseOrderController@showPurchaseOrder');


Route::group(['middleware' => ['auth']], function (){
    //    po
    Route::get('/generate-po/{quotation_id}', 'PurchaseOrderController@generatePo');
    Route::get('/approve-po/{purchase_order_id}', 'PurchaseOrderController@approvePurchaseOrder');
    Route::get('/disapprove-po/{purchase_order_id}', 'PurchaseOrderController@disapprovePurchaseOrder');

    Route::get('/', 'HomeController@dashboard');
    Route::resource('/customers', 'CustomerController');
    Route::resource('/manage-users', 'ManageController');
    Route::get('/create-role', 'ManageController@createRole');
    Route::delete('delete-role/{id}', 'ManageController@deleteRole');
    Route::get('/roles', 'ManageController@roleIndex');
    Route::post('/store-role', 'ManageController@storeRole');
    Route::get('/customer-request/{customer_id}/{customer_type}', 'CustomerRequestController@customerRequest');
    Route::resource('/good-types', 'GoodTypeController');
    Route::resource('/container-types', 'ContainerTypeController');
    Route::resource('/leads', 'LeadController');
    Route::resource('/tariffs', 'TariffController');
    Route::resource('/departments', 'DepartmentController');
    Route::post('/search-lead', 'LeadController@searchLeads');
    Route::post('/error', 'DepartmentController@error');
    Route::post('/search-dms', 'DmsController@searchDms');
    Route::post('/update-berth', 'DmsController@updateBerth');
    Route::post('/search-customer', 'CustomerController@ajaxSearch');
    Route::get('/get-customer/{dclink}', 'CustomerController@getCustomer');
    Route::get('/get-vendor/{id}', 'PurchaseOrderController@getVendor');
    Route::post('/search-vendor', 'PurchaseOrderController@searchSupplier');
    Route::post('/add-purchase-order', 'PurchaseOrderController@addPurchaseOrder');
    Route::post('/update-vessel-details', 'CustomerController@updateVessel');
    Route::post('/vessel-details', 'CustomerController@vesselDetails');
    Route::post('/others-vessel-details', 'CustomerController@oVesselDetails');
    Route::post('/voyage-details', 'CustomerController@voyageDetails');
    Route::post('/consignee-details', 'CustomerController@consigneeDetails');
    Route::post('/cargo-details', 'CustomerController@cargoDetails');
    Route::post('/update-cargo-details', 'CustomerController@updateCargoDetails');
    Route::post('/delete-cargo', 'CustomerController@deleteCargo');
    Route::post('/quotation-service', 'QuotationServiceController@addQuotationService');
    Route::post('/quotation-service-delete', 'QuotationServiceController@deleteQuotationService');
    Route::get('/quotation/{id}', 'QuotationController@showQuotation');
    Route::get('/proforma/{id}', 'ProformaController@showQuotation');
    Route::get('/my-pdas', 'QuotationController@myPdas');
    Route::get('/all-pdas', 'QuotationController@allPdas');
    Route::get('/pdas/{status}', 'QuotationController@pdaStatus');
    Route::get('/quotation/view/{id}', 'QuotationController@viewQuotation');
    Route::post('/client/quotation/send/', 'QuotationController@sendToCustomer');
    Route::get('/all-notifications', 'NotificationController@index');
    Route::get('/agency', 'AgencyController@index');
    Route::post('/agency/approve', 'AgencyApprovalController@approve');
    Route::post('/agency/remark', 'AgencyApprovalController@addRemark');
    Route::post('/agency/disapprove', 'AgencyApprovalController@revision');
    Route::post('/agency/checked', 'AgencyApprovalController@checked');
    Route::get('/notifications/{id}', 'NotificationController@show');
    Route::get('/quotation/request/{id}', 'QuotationController@requestQuotation');
//Route::get('/quotation/{id}/pdf', 'QuotationController@pdfQuotation');
    Route::post('/update-service', 'QuotationServiceController@updateService');
    Route::post('/notifying', 'NotifyingPartyController@notifying');

//next stage
    Route::get('/quotation/convert/{id}', 'QuotationController@convertCustomer');
    Route::get('/bill-of-lading/{id}', 'BillOfLandingController@edit');
    Route::get('/test/', 'BillOfLandingController@test');
//dms
    Route::get('/dms', 'DmsController@index');
    Route::get('/dms/edit/{id}', 'DmsController@edit');
    Route::get('/dms/complete/{id}', 'DmsController@complete');
    Route::get('/generate/laytime/{id}', 'DmsController@generateLayTime');
    Route::get('/generate/sof/{id}', 'DmsController@generateSof');
    Route::post('/dms/store/', 'DmsController@store');
    Route::post('/dms/add/sof', 'DmsController@addSof');
    Route::get('/dms/delete/sof/{id}', 'DmsController@deleteSof');
    Route::post('/update-dms/', 'DmsController@updateDms');
    Route::post('/vessel/doc/upload/', 'VesselDocsController@upload');
    Route::post('/add-remittance', 'QuotationController@addRemittance');
    Route::post('/reduce-remittance', 'QuotationController@reduceRemittance');
    Route::post('/consignee/do', 'GenerateDocument@doDoc');
    Route::post('/consignee/edo', 'GenerateDocument@edoDoc');
    Route::post('/generate-documents/cfs-ro', 'GenerateDocument@cfsDoc');
    Route::post('/generate-documents/manifest-in', 'GenerateDocument@inmanifestDoc');
//stage
    Route::resource('/stages', 'StageController');
    Route::resource('/other-services-type', 'ExtraServiceTypeController');
    Route::resource('/other-services', 'ExtraServiceController');
    Route::resource('/stage-components', 'StageComponentController');
//generate docs
    Route::get('/generate-documents/{type}/{id}', 'GenerateDocument@generateDocument');
    Route::resource('/project-cost', 'PettyCashController');
    Route::get('/approve-project-cost-request/{petty_cash_id}', 'PettyCashController@approve');
    Route::post('/service-cost', 'QuotationController@serviceCost');
});

app/Http/Controllers/ContainerTypeController.php
<?php

namespace App\Http\Controllers;

use App\ContainerType;
use Illuminate\Http\Request;

class ContainerTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('container-type.index')
            ->withTypes(ContainerType::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('container-type.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        ContainerType::create($request->all());

        return redirect('/container-types');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ContainerType  $containerType
     * @return \Illuminate\Http\Response
     */
    public function show(ContainerType $containerType)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ContainerType  $containerType
     * @return \Illuminate\Http\Response
     */
    public function edit(ContainerType $containerType)
    {
        return view('container-type.edit')
            ->withType($containerType);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ContainerType  $containerType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ContainerType $containerType)
    {
        $containerType->update($request->all());

        return redirect('/container-types');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ContainerType  $containerType
     * @return \Illuminate\Http\Response
     */
    public function destroy(ContainerType $containerType)
    {
        $containerType->delete();

        return redirect('/container-types');
    }
}

resources/views/container-type/create.blade.php
@extends('layouts.main')
@section('content')
    <div class="row page-titles m-b-0">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Dashboard</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </div>
        <div>
            <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Container Type</h4>
                        <form class="form-material m-t-40" action="{{ route('container-types.store') }}" method="post">
                            {{ csrf_field() }}
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        <input type="text" required id="name" name="name" class="form-control" placeholder="Name">
                                    </div>
                                </div>

                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="description">Description</label>
                                            <input type="text" required id="description" name="description" class="form-control" placeholder="Description">
                                        </div>
                                        <div class="form-group">
                                            <br>
                                            <input class="btn pull-right btn-primary" type="submit" value="Save">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/container-type/edit.blade.php
@extends('layouts.main')
@section('content')
    <div class="row page-titles m-b-0">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Dashboard</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </div>
        <div>
            <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Container Type</h4>
                        <form class="form-material m-t-40" action="{{ route('container-types.update', $type->id) }}" method="post">
                            {{ csrf_field() }}
                            {{ method_field('put') }}
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        <input type="text" required id="name" value="{{$type->name}}" name="name" class="form-control" placeholder="Name">
                                    </div>
                                </div>

                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <input type="text" required id="description" value="{{$type->description}}" name="description" class="form-control" placeholder="Description">
                                    </div>
                                    <div class="form-group">
                                        <br>
                                        <input class="btn pull-right btn-primary" type="submit" value="Save">
                                    </div>
                                </div>
                            </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/container-type/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="row page-titles m-b-0">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Dashboard</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </div>
        <div>
            <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Container Types <a href="{{ route('container-types.create') }}" class="btn btn-primary pull-right">Add Container Type</a></h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Description</th>
                                    <th>Created</th>
                                    <th class="text-right">Action</th>
                                </tr>
                                </thead>
                                <tbody id="customers">
                                @foreach($types as $goodtype)
                                    <tr>
                                        <td>{{ ucwords($goodtype->name) }}</td>
                                        <td>{{ ucfirst($goodtype->description) }}</td>
                                        <td>{{ \Carbon\Carbon::parse($goodtype->created_at)->format('d-M-y') }}</td>
                                        <td class="text-right">
                                            <form action="{{ route('container-types.destroy', $goodtype->id) }}" method="post">
                                                <a href=" {{ route('container-types.edit', $goodtype->id) }}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                @can('can-delete')
                                                    <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                                                    @endcan
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/container-type/show.blade.php
@extends('layouts.main')
@section('content')
    <div class="row page-titles m-b-0">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Dashboard</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </div>
        <div>
            <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Lead {{ ucwords($lead->name) }}</h4>
                        <table class="table table-borded">
                            <tr>
                                <td><strong>Name : </strong> {{ ucwords($lead->name) }}</td>
                                <td><strong>Contact Person : </strong> {{ ucwords($lead->contact_person) }}</td>
                            </tr>
                            <tr>
                                <td><strong>Address : </strong> {{ ucwords($lead->address) }}</td>
                                <td><strong>Phone : </strong> {{ $lead->phone }}</td>
                            </tr>
                            <tr>
                                <td><strong>Telephone : </strong> {{ $lead->telephone }}</td>
                                <td><strong>Location : </strong> {{ $lead->location }}</td>
                            </tr>
                        </table>

                        <div class="col-sm-8">
                            <a href="{{ url('/customer-request/'.$lead->id.'/'.\Esl\helpers\Constants::LEAD_CUSTOMER) }}" class="btn btn-primary">Generate Quotation</a>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>NO</th>
                                    <th>Vessel</th>
                                    <th>Quotation Status</th>
                                    <th>Created On</th>
                                    <th class="text-nowrap">Action</th>
                                </tr>
                                </thead>
                                <tbody id="customers">
                                @foreach($quotations->quotation as $quotation)
                                        <tr>
                                            <td>ESL00{{ ucwords($quotation->id) }}</td>
                                            <td>{{ ucfirst($quotation->vessel->name) }}</td>
                                            <td>{{ ucfirst($quotation->status) }}</td>
                                            <td>{{ \Carbon\Carbon::parse($quotation->created_at)->format('d-M-y') }}</td>
                                            <td class="text-nowrap">
                                                    <a href=" {{ url('/quotation/'. $quotation->id) }}" class="btn btn-sm btn-info"><i class="fa fa-eye"></i></a>
                                            </td>
                                        </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection