routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Mail\ApprovalRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;

Auth::routes();

//Route::get('/',function(){
//
//    Mail::to(['email'=>'marvincollins14@gmail.com'])
//        ->cc(\Esl\helpers\Constants::EMAILS_CC)
//        ->send(new \App\Mail\ProjectInvoice(['message'=>'System Under Maintenance',
//            'body'=>'System is Down for Maintenance'],'System Under maintenance'));
//    return view('404');
//
//
////    echo "check your mailtrap";
//
//});

Route::get('/testmail',function(){
    Mail::to(['email'=>'marvincollins14@gmail.com'])
        ->cc(['evans.ngala@esl-eastafrica.com'])
        ->send(new ApprovalRequest([
            'user' => 'Demo Demo',
            'url'=>'/quotation/view/1'],'Approval Request'));

    echo "check your mailtrap";

});
Route::get('/quotation/preview/{id}', 'QuotationController@previewQuotation');
Route::get('/quotation/download/{id}', 'QuotationController@downloadQuotation');
Route::get('/proforma/download/{id}', 'ProformaController@downloadProforma');
Route::get('/quotation/customer/accepted/{id}', 'QuotationController@customerAccept');
Route::get('/quotation/customer/declined/{id}', 'QuotationController@customerDecline');
Route::get('/view-po/{purchase_order_id}', 'PurchaseOrderController@showPurchaseOrder');


Route::group(['middleware' => ['auth']], function (){
    //    po
    Route::get('/generate-po/{quotation_id}', 'PurchaseOrderController@generatePo');
    Route::get('/approve-po/{purchase_order_id}', 'PurchaseOrderController@approvePurchaseOrder');
    Route::get('/disapprove-po/{purchase_order_id}', 'PurchaseOrderController@disapprovePurchaseOrder');

    Route::get('/', 'HomeController@dashboard');
    Route::resource('/customers', 'CustomerController');
    Route::resource('/manage-users', 'ManageController');
    Route::get('/create-role', 'ManageController@createRole');
    Route::delete('delete-role/{id}', 'ManageController@deleteRole');
    Route::get('/roles', 'ManageController@roleIndex');
    Route::post('/store-role', 'ManageController@storeRole');
    Route::get('/customer-request/{customer_id}/{customer_type}', 'CustomerRequestController@customerRequest');
    Route::resource('/good-types', 'GoodTypeController');
    Route::resource('/container-types', 'ContainerTypeController');
    Route::resource('/leads', 'LeadController');
    Route::resource('/tariffs', 'TariffController');
    Route::resource('/departments', 'DepartmentController');
    Route::post('/search-lead', 'LeadController@searchLeads');
    Route::post('/error', 'DepartmentController@error');
    Route::post('/search-dms', 'DmsController@searchDms');
    Route::post('/update-berth', 'DmsController@updateBerth');
    Route::post('/search-customer', 'CustomerController@ajaxSearch');
    Route::get('/get-customer/{dclink}', 'CustomerController@getCustomer');
    Route::get('/get-vendor/{id}', 'PurchaseOrderController@getVendor');
    Route::post('/search-vendor', 'PurchaseOrderController@searchSupplier');
    Route::post('/add-purchase-order', 'PurchaseOrderController@addPurchaseOrder');
    Route::post('/update-vessel-details', 'CustomerController@updateVessel');
    Route::post('/vessel-details', 'CustomerController@vesselDetails');
    Route::post('/others-vessel-details', 'CustomerController@oVesselDetails');
    Route::post('/voyage-details', 'CustomerController@voyageDetails');
    Route::post('/consignee-details', 'CustomerController@consigneeDetails');
    Route::post('/cargo-details', 'CustomerController@cargoDetails');
    Route::post('/update-cargo-details', 'CustomerController@updateCargoDetails');
    Route::post('/delete-cargo', 'CustomerController@deleteCargo');
    Route::post('/quotation-service', 'QuotationServiceController@addQuotationService');
    Route::post('/quotation-service-delete', 'QuotationServiceController@deleteQuotationService');
    Route::get('/quotation/{id}', 'QuotationController@showQuotation');
    Route::get('/proforma/{id}', 'ProformaController@showQuotation');
    Route::get('/my-pdas', 'QuotationController@myPdas');
    Route::get('/all-pdas', 'QuotationController@allPdas');
    Route::get('/pdas/{status}', 'QuotationController@pdaStatus');
    Route::get('/quotation/view/{id}', 'QuotationController@viewQuotation');
    Route::post('/client/quotation/send/', 'QuotationController@sendToCustomer');
    Route::get('/all-notifications', 'NotificationController@index');
    Route::get('/agency', 'AgencyController@index');
    Route::post('/agency/approve', 'AgencyApprovalController@approve');
    Route::post('/agency/remark', 'AgencyApprovalController@addRemark');
    Route::post('/agency/disapprove', 'AgencyApprovalController@revision');
    Route::post('/agency/checked', 'AgencyApprovalController@checked');
    Route::get('/notifications/{id}', 'NotificationController@show');
    Route::get('/quotation/request/{id}', 'QuotationController@requestQuotation');
//Route::get('/quotation/{id}/pdf', 'QuotationController@pdfQuotation');
    Route::post('/update-service', 'QuotationServiceController@updateService');
    Route::post('/notifying', 'NotifyingPartyController@notifying');

//next stage
    Route::get('/quotation/convert/{id}', 'QuotationController@convertCustomer');
    Route::get('/bill-of-lading/{id}', 'BillOfLandingController@edit');
    Route::get('/test/', 'BillOfLandingController@test');
//dms
    Route::get('/dms', 'DmsController@index');
    Route::get('/dms/edit/{id}', 'DmsController@edit');
    Route::get('/dms/complete/{id}', 'DmsController@complete');
    Route::get('/generate/laytime/{id}', 'DmsController@generateLayTime');
    Route::get('/generate/sof/{id}', 'DmsController@generateSof');
    Route::post('/dms/store/', 'DmsController@store');
    Route::post('/dms/add/sof', 'DmsController@addSof');
    Route::get('/dms/delete/sof/{id}', 'DmsController@deleteSof');
    Route::post('/update-dms/', 'DmsController@updateDms');
    Route::post('/vessel/doc/upload/', 'VesselDocsController@upload');
    Route::post('/add-remittance', 'QuotationController@addRemittance');
    Route::post('/reduce-remittance', 'QuotationController@reduceRemittance');
    Route::post('/consignee/do', 'GenerateDocument@doDoc');
    Route::post('/consignee/edo', 'GenerateDocument@edoDoc');
    Route::post('/generate-documents/cfs-ro', 'GenerateDocument@cfsDoc');
    Route::post('/generate-documents/manifest-in', 'GenerateDocument@inmanifestDoc');
//stage
    Route::resource('/stages', 'StageController');
    Route::resource('/other-services-type', 'ExtraServiceTypeController');
    Route::resource('/other-services', 'ExtraServiceController');
    Route::resource('/stage-components', 'StageComponentController');
//generate docs
    Route::get('/generate-documents/{type}/{id}', 'GenerateDocument@generateDocument');
    Route::resource('/project-cost', 'PettyCashController');
    Route::get('/approve-project-cost-request/{petty_cash_id}', 'PettyCashController@approve');
    Route::post('/service-cost', 'QuotationController@serviceCost');
});

app/Lead.php
<?php

namespace App;

use Esl\Repository\ESLModel;
use Illuminate\Database\Eloquent\Model;

class Lead extends ESLModel
{
    protected  $fillable = ['name','contact_person','phone','currency',
        'email','telephone','prospect_id','client_id','cPhysicalAddress1','cPhysicalAddress2'];

    public function quotation()
    {
        return $this->hasMany(Quotation::class, 'lead_id','id');
    }
}

app/Http/Controllers/LeadController.php
<?php

namespace App\Http\Controllers;

use App\Lead;
use App\Quotation;
use Carbon\Carbon;
use Esl\helpers\Constants;
use Esl\Repository\CustomersRepo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class LeadController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
//        dd(Constants::COUNTRY_LIST);
        return view('leads.index')
            ->withLeads(Lead::where('status',0)->simplePaginate(25));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
//        dd(json_decode(Constants::CURRENCY_ARRAY));
        return view('leads.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        $inserted = $request->has('client_id') ? $request->client_id : DB::connection('sqlsrv2')->table('_rtblProspect')->insertGetId([
//            'cCompanyName'=> mb_strimwidth($request->name, 4,10),
//            'cEmail'=> $request->email,
//            'cPhysicalAddress1'=> $request->cPhysicalAddress1,
//            'cPhysicalAddress2'=> $request->cPhysicalAddress2,
//            'cTelephone'=> $request->phone
//        ]);

        $data = $request->all();
        $data['prospect_id'] = $request->has('client_id') ? null : null;
        $data['client_id'] = $request->has('client_id') ? $request->client_id : null;
        $lead = Lead::create($data);
        return redirect('/leads/'.$lead->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Lead  $lead
     * @return \Illuminate\Http\Response
     */
    public function show(Lead $lead)
    {
        return view('leads.show')
            ->withLead($lead)
            ->withQuotations(Lead::with(['quotation.vessel'])->findOrFail($lead->id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Lead  $lead
     * @return \Illuminate\Http\Response
     */
    public function edit(Lead $lead)
    {
        return view('leads.edit')
            ->withLead($lead);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Lead  $lead
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Lead $lead)
    {
        //TODO:Update the prospect leader
//        if ($lead->prospect_id != null){
//            dd(DB::connection('sqlsrv2')->table('_rtblProspect')->where(''$lead->prospect_id));
//        };
        $lead->update($request->all());

        return redirect('/leads');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Lead  $lead
     * @return \Illuminate\Http\Response
     */
    public function destroy(Lead $lead)
    {
        $lead->status = 1;
        $lead->save();
        return redirect('/leads');
    }

    public function searchLeads(Request $request)
    {
        $search_result = CustomersRepo::customerInit()->searchCustomers($request->search_item, 'leads');

        $output = "";
        foreach ($search_result as $item){

            $output .= '<tr>'.
                '<td>'. ucwords($item->name).'</td>'.
                '<td>'.ucfirst($item->contact_person).'</td>'.
                '<td>'.$item->phone.'</td>'.
                '<td>'.$item->email.'</td>'.
//                '<td>'.$item->address.'</td>'.
                '<td>'.$item->telephone.'</td>'.
//                '<td>'.$item->location.'</td>'.
                '<td>'.Carbon::parse($item->created_at)->format('d-M-y').'</td>'.
                '<td>'.
'<form action="'.route('leads.destroy', $item->id).'" method="post">'.
                '<a href="'.route('leads.show', $item->id).'" class="btn btn-sm btn-info"><i class="fa fa-eye"></i></a>'.
                                                '<a href="'.route('leads.edit', $item->id).'" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>'.
                                                csrf_field().'<br>'.
                                                method_field('DELETE').
                                                '<button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>'.
                                            '</form></td>'.
                '</tr>';
        }

        return Response(['output' => $output]);
    }
}

resources/views/leads/create.blade.php
@extends('layouts.main')
@section('content')
    <div class="row page-titles m-b-0">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Dashboard</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </div>
        <div>
            <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add Lead</h4>
                        <form class="form-material m-t-40" action="{{ route('leads.store') }}" method="post">
                            {{ csrf_field() }}
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="name">Name <span class="help">(Customer or Company Name)</span></label>
                                        <input type="text" required id="name" name="name" class="form-control" placeholder="Name">
                                        {{--<span class="help-block text-muted">--}}
                                        {{--<small>A block of help text that breaks onto a new line and may extend beyond one line.</small>--}}
                                        {{--</span>--}}
                                    </div>
                                    <div class="form-group">
                                        <label for="contact_person">Contact Person</label>
                                        <input type="text" required id="contact_person" name="contact_person" class="form-control" placeholder="Contact Person">
                                        {{--<span class="help-block text-muted">--}}
                                        {{--<small>A block of help text that breaks onto a new line and may extend beyond one line.</small>--}}
                                        {{--</span>--}}
                                    </div>
                                    <div class="form-group">
                                        <label for="email">Email </label>
                                        <input type="text" required id="email" name="email" class="form-control" placeholder="Email">
                                        {{--<span class="help-block text-muted">--}}
                                        {{--<small>A block of help text that breaks onto a new line and may extend beyond one line.</small>--}}
                                        {{--</span>--}}
                                    </div>
                                    <div class="form-group">
                                        <label for="phone">Phone </label>
                                        <input type="text" required id="phone" name="phone" class="form-control" placeholder="Phone">
                                        {{--<span class="help-block text-muted">
                                            <small>A block of help text that breaks onto a new line and may extend beyond one line.</small>
                                        </span>--}}
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="telephone">Telephone </label>
                                        <input type="text" id="telephone" name="telephone" class="form-control" placeholder="Telephone">
                                        {{--<span class="help-block text-muted">--}}
                                        {{--<small>A block of help text that breaks onto a new line and may extend beyond one line.</small>--}}
                                        {{--</span>--}}
                                    </div>

                                    <div class="form-group">
                                        <label for="cPhysicalAddress1">Address 1</label>
                                        <input type="text" id="cPhysicalAddress1" name="cPhysicalAddress1" class="form-control" placeholder="Address 1">
                                        {{--<span class="help-block text-muted">--}}
                                        {{--<small>A block of help text that breaks onto a new line and may extend beyond one line.</small>--}}
                                        {{--</span>--}}
                                    </div>
                                    <div class="form-group">
                                        <label for="cPhysicalAddress2">Address 2</label>
                                        <input type="text" id="cPhysicalAddress2" name="cPhysicalAddress2" class="form-control" placeholder="Address 2 ">
                                        {{--<span class="help-block text-muted">--}}
                                        {{--<small>A block of help text that breaks onto a new line and may extend beyond one line.</small>--}}
                                        {{--</span>--}}
                                    </div>
                                    <div class="form-group">
                                        <label for="currency">Select Currency </label>
                                        <select name="currency" required id="currency" class="form-control select2">
                                            <option value="">Select Currency</option>
                                            @foreach(json_decode(\Esl\helpers\Constants::CURRENCY_ARRAY) as $value)
                                                <option value="{{$value->code}}">{{ $value->name_plural }}</option>
                                                @endforeach
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <br>
                                        <input class="btn pull-right btn-primary" type="submit" value="Save">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/leads/edit.blade.php
@extends('layouts.main')
@section('content')
    <div class="row page-titles m-b-0">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Dashboard</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </div>
        <div>
            <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Edit Lead</h4>
                        <form class="form-material m-t-40" action="{{ route('leads.update', $lead->id) }}" method="post">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="name">Name <span class="help">(Customer or Company Name)</span></label>
                                        <input type="text" required id="name" value="{{ $lead->name }}" name="name" class="form-control" placeholder="Name">
                                        {{--<span class="help-block text-muted">--}}
                                        {{--<small>A block of help text that breaks onto a new line and may extend beyond one line.</small>--}}
                                        {{--</span>--}}
                                    </div>
                                    <div class="form-group">
                                        <label for="contact_person">Contact Person</label>
                                        <input type="text" required id="contact_person" value="{{ $lead->contact_person }}" name="contact_person" class="form-control" placeholder="Contact Person">
                                        {{--<span class="help-block text-muted">--}}
                                        {{--<small>A block of help text that breaks onto a new line and may extend beyond one line.</small>--}}
                                        {{--</span>--}}
                                    </div>
                                    <div class="form-group">
                                        <label for="email">Email </label>
                                        <input type="text" required id="email" name="email" value="{{ $lead->email }}" class="form-control" placeholder="Email">
                                        {{--<span class="help-block text-muted">--}}
                                        {{--<small>A block of help text that breaks onto a new line and may extend beyond one line.</small>--}}
                                        {{--</span>--}}
                                    </div>
                                    <div class="form-group">
                                        <label for="phone">Phone </label>
                                        <input type="text" required id="phone" name="phone" value="{{ $lead->phone }}" class="form-control" placeholder="Phone">
                                        {{--<span class="help-block text-muted">
                                            <small>A block of help text that breaks onto a new line and may extend beyond one line.</small>
                                        </span>--}}
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label for="telephone">Telephone </label>
                                        <input type="text" id="telephone" name="telephone" value="{{ $lead->telephone }}" class="form-control" placeholder="Telephone">
                                        {{--<span class="help-block text-muted">--}}
                                        {{--<small>A block of help text that breaks onto a new line and may extend beyond one line.</small>--}}
                                        {{--</span>--}}
                                    </div>
                                    <div class="form-group">
                                        <label for="cPhysicalAddress1">Address 1</label>
                                        <input type="text" id="cPhysicalAddress1" name="cPhysicalAddress1" value="{{ $lead->cPhysicalAddress1 }}" class="form-control" placeholder="Address 1">
                                        {{--<span class="help-block text-muted">--}}
                                        {{--<small>A block of help text that breaks onto a new line and may extend beyond one line.</small>--}}
                                        {{--</span>--}}
                                    </div>
                                    <div class="form-group">
                                        <label for="cPhysicalAddress2">Address 2 </label>
                                        <input type="text" id="cPhysicalAddress2" name="cPhysicalAddress2" value="{{ $lead->cPhysicalAddress2 }}" class="form-control" placeholder="Address 2">
                                        {{--<span class="help-block text-muted">--}}
                                        {{--<small>A block of help text that breaks onto a new line and may extend beyond one line.</small>--}}
                                        {{--</span>--}}
                                    </div>
                                    <div class="form-group">
                                        <label for="currency">Select Currency </label>
                                        <select name="currency" required id="currency" class="form-control select2">
                                            <option value="">Select Currency</option>
                                            @foreach(json_decode(\Esl\helpers\Constants::CURRENCY_ARRAY) as $value)
                                                <option value="{{$value->code}}">{{ $value->name_plural }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <br>
                                        <input class="btn pull-right btn-primary" type="submit" value="Update">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/leads/index.blade.php
@extends('layouts.main')
@section('content')
    <div class="row page-titles m-b-0">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Dashboard</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </div>
        <div>
            <button class="right-side-toggle waves-effect waves-light btn-inverse btn btn-circle btn-sm pull-right m-l-10"><i class="ti-settings text-white"></i></button>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Leads <a href="{{ route('leads.create') }}" class="btn btn-primary pull-right">Add Lead</a></h4>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    Search : <input type="text" id="search_lead">
                                </div>
                            </div>
                        </div>
                        <hr>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Contact Person</th>
                                    {{--<th>Phone</th>--}}
                                    {{--<th>Email</th>--}}
                                    {{--<th>Address</th>--}}
                                    <th>Telephone</th>
                                    {{--<th>Physical Location</th>--}}
                                    <th>Created</th>
                                    <th class="text-right">Action</th>
                                </tr>
                                </thead>
                                <tbody id="customers">
                                @foreach($leads->sortBy('index') as $lead)
                                    <tr>
                                        <td>{{ ucwords($lead->name) }}</td>
                                        <td>{{ ucfirst($lead->contact_person) }}</td>
                                        {{--<td>{{ $lead->phone }}</td>--}}
                                        {{--<td>{{ $lead->email }}</td>--}}
{{--                                        <td>{{ $lead->address }}</td>--}}
                                        <td>{{ $lead->telephone }}</td>
{{--                                        <td>{{ $lead->location }}</td>--}}
                                        <td>{{ \Carbon\Carbon::parse($lead->created_at)->format('d-M-y') }}</td>
                                        <td class="text-right">
                                            <form action="{{ route('leads.destroy', $lead->id) }}" method="post">
                                                <a href=" {{ route('leads.show', $lead->id) }}" class="btn btn-sm btn-info"><i class="fa fa-eye"></i></a>
                                                <a href=" {{ route('leads.edit', $lead->id) }}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                @can('can-delete')
                                                    <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
@endcan
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="footable pagination">
                                {{ $leads->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        var customer = $('#search_lead');

        customer.on('keyup', function () {
            axios.post('{{ url('/search-lead') }}',{
                'search_item': customer.val()
            }).then( function (response) {
                $('#customers').empty().append(response.data.output);
            })
                .catch( function (error) {
                    console.log(error)
                });
        });
    </script>
@endsection